name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "REPLIERS_API_TOKEN=${{ secrets.REPLIERS_API_TOKEN }}" >> .env
          echo "CACHE_REDIS_HOST=redis://cache" >> .env
          echo "TIME_DELAY=15" >> .env
          echo "USE_CACHE=True" >> .env
          echo "RETRIES=5" >> .env

      - name: Set up SSH
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          set -x 
          if ! command -v ssh &> /dev/null; then
              echo "SSH не установлен. Установка..."
              sudo apt-get update -y
              sudo apt-get install -y openssh-client
          fi

          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts || { echo "Ошибка при получении ключа хоста"; exit 1; }

      - name: Copy files to server
        env:
            SERVER_USER: ${{ secrets.SERVER_USER }}
            SERVER_IP: ${{ secrets.SERVER_IP }}
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
            TARGET_DIR: /home/${{ secrets.SERVER_USER }}/RepliersParser
        run: |
            scp -P "$SERVER_PORT" ./.env "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
            scp -P "$SERVER_PORT" ./api.py "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
            scp -P "$SERVER_PORT" ./replier_parser.py "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
            scp -P "$SERVER_PORT" ./Dockerfile "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
            scp -P "$SERVER_PORT" ./docker-compose.yml "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
            scp -P "$SERVER_PORT" ./requirements.txt "$SERVER_USER@$SERVER_IP:$TARGET_DIR"

      - name: Restart Docker containers
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }} 
        run: |
          if ! ssh -p "$SERVER_PORT" "$SERVER_USER@$SERVER_IP" << 'ENDSSH'
          cd "$TARGET_DIR"
          docker-compose down
          docker-compose up -d --build
          ENDSSH
          then
              echo "Ошибка при перезапуске контейнеров." >&2
              exit 1
          fi
