name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "REPLIERS_API_TOKEN=${{ secrets.REPLIERS_API_TOKEN }}" >> .env
          echo "CACHE_REDIS_HOST=redis://cache" >> .env
          echo "TIME_DELAY=15" >> .env
          echo "USE_CACHE=True" >> .env
          echo "RETRIES=5" >> .env

      - name: Copy files to server
        env:
            SERVER_USER: ${{ secrets.SERVER_USER }}
            SERVER_IP: ${{ secrets.SERVER_IP }}
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
            TARGET_DIR: /home/${{ secrets.SERVER_USER }}/RepliersParser
        run: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > pk
            chmod 600 pk
            scp -i pk -P "$SERVER_PORT" ./.env "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
            scp -i pk -P "$SERVER_PORT" ./api.py "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
            scp -i pk -P "$SERVER_PORT" ./replier_parser.py "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
            scp -i pk -P "$SERVER_PORT" ./Dockerfile "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
            scp -i pk -P "$SERVER_PORT" ./docker-compose.yml "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
            scp -i pk -P "$SERVER_PORT" ./requirements.txt "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
            rm -f pk

      - name: Restart Docker containers
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }} 
        run: |
          if ! ssh -p "$SERVER_PORT" "$SERVER_USER@$SERVER_IP" << 'ENDSSH'
          cd "$TARGET_DIR"
          docker-compose down
          docker-compose up -d --build
          ENDSSH
          then
              echo "Ошибка при перезапуске контейнеров." >&2
              exit 1
          fi
